/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.

 */
package telas;

import java.io.FileOutputStream;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import util.HibernateUtil;

/**
 *
 * @author alexandre
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxContasPeriodo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxInicioAno = new javax.swing.JComboBox();
        jComboBoxInicioMes = new javax.swing.JComboBox();
        jComboBoxInicioDia = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxFimAno = new javax.swing.JComboBox();
        jComboBoxFimMes = new javax.swing.JComboBox();
        jComboBoxFimDia = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxStatusAberta = new javax.swing.JCheckBox();
        jCheckBoxStatusFeixada = new javax.swing.JCheckBox();
        jCheckBoxStatusTodas = new javax.swing.JCheckBox();
        jCheckBoxContasStatus = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxSocio = new javax.swing.JComboBox();
        jCheckBoxContasSocio = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jComboBoxLogradouro = new javax.swing.JComboBox();
        jCheckBoxContasLogradouro = new javax.swing.JCheckBox();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Emissão de contas"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodo"));

        jCheckBoxContasPeriodo.setText("Considerar Periodo");
        jCheckBoxContasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContasPeriodoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio"));

        jComboBoxInicioAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
            "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
            "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029",
            "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039",
            "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049",
            "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059"
        }));
        jComboBoxInicioAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInicioAnoActionPerformed(evt);
            }
        });

        jComboBoxInicioMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "Janeiro",
            "Fevereiro",
            "Março",
            "Abril",
            "Maio",
            "Junho",
            "Julho",
            "Agosto",
            "Setembro",
            "Novembro",
            "Outubro",
            "Dezembro"
        }));
        jComboBoxInicioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInicioMesActionPerformed(evt);
            }
        });

        jComboBoxInicioDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "01","02","03","04","05","06","07","08","09","10",
            "11","12","13","14","15","16","17","18","19","20",
            "21","22","23","24","25","26","27","28","29","30",
            "31",

        }));
        jComboBoxInicioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInicioDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jComboBoxInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInicioAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxInicioAno)
                    .addComponent(jComboBoxInicioDia)
                    .addComponent(jComboBoxInicioMes)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Fim"));

        jComboBoxFimAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
            "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
            "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029",
            "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039",
            "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049",
            "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059"
        }));
        jComboBoxFimAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFimAnoActionPerformed(evt);
            }
        });

        jComboBoxFimMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "Janeiro",
            "Fevereiro",
            "Março",
            "Abril",
            "Maio",
            "Junho",
            "Julho",
            "Agosto",
            "Setembro",
            "Novembro",
            "Outubro",
            "Dezembro"
        }));
        jComboBoxFimMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFimMesActionPerformed(evt);
            }
        });

        jComboBoxFimDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "",
            "01","02","03","04","05","06","07","08","09","10",
            "11","12","13","14","15","16","17","18","19","20",
            "21","22","23","24","25","26","27","28","29","30",
            "31",

        }));
        jComboBoxFimDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFimDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jComboBoxFimDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFimMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFimAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxFimDia)
                .addComponent(jComboBoxFimMes)
                .addComponent(jComboBoxFimAno))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxContasPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jCheckBoxContasPeriodo)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Paga/Aberta /Todas"));

        jCheckBoxStatusAberta.setText("Abertas");
        jCheckBoxStatusAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusAbertaActionPerformed(evt);
            }
        });

        jCheckBoxStatusFeixada.setText("Feixadas");
        jCheckBoxStatusFeixada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusFeixadaActionPerformed(evt);
            }
        });

        jCheckBoxStatusTodas.setText("Todas");
        jCheckBoxStatusTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusTodasActionPerformed(evt);
            }
        });

        jCheckBoxContasStatus.setText("Considerar Status");
        jCheckBoxContasStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContasStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxContasStatus)
                .addGap(52, 52, 52)
                .addComponent(jCheckBoxStatusAberta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxStatusFeixada)
                .addGap(73, 73, 73)
                .addComponent(jCheckBoxStatusTodas)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxStatusAberta)
                        .addComponent(jCheckBoxStatusFeixada)
                        .addComponent(jCheckBoxStatusTodas))
                    .addComponent(jCheckBoxContasStatus))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Socio"));

        jComboBoxSocio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSocioActionPerformed(evt);
            }
        });

        jCheckBoxContasSocio.setText("Considerar Socio");
        jCheckBoxContasSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContasSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxContasSocio)
                .addGap(58, 58, 58)
                .addComponent(jComboBoxSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxContasSocio))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Gerar Relatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Logradouro"));

        jComboBoxLogradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLogradouroActionPerformed(evt);
            }
        });

        jCheckBoxContasLogradouro.setText("Considerar Logradouro");
        jCheckBoxContasLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContasLogradouroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxContasLogradouro)
                .addGap(28, 28, 28)
                .addComponent(jComboBoxLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxContasLogradouro))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxStatusTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusTodasActionPerformed
        
        if(!jCheckBoxStatusTodas.isSelected())
        {
         jCheckBoxContasStatus.setSelected(false);
        }
        else
        {
         jCheckBoxStatusFeixada.setSelected(false);
         jCheckBoxStatusAberta.setSelected(false);
         jCheckBoxContasStatus.setSelected(true);
        } 
    }//GEN-LAST:event_jCheckBoxStatusTodasActionPerformed

    private void jComboBoxSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSocioActionPerformed
        jCheckBoxContasSocio.setSelected(true);
    }//GEN-LAST:event_jComboBoxSocioActionPerformed

    private void jCheckBoxStatusAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusAbertaActionPerformed
     
        if(!jCheckBoxStatusAberta.isSelected())
        {
         jCheckBoxContasStatus.setSelected(false);
        }
        else
        {
         jCheckBoxStatusFeixada.setSelected(false);
         jCheckBoxStatusTodas.setSelected(false);
         jCheckBoxContasStatus.setSelected(true);
        } 
        
    }//GEN-LAST:event_jCheckBoxStatusAbertaActionPerformed

    private void jCheckBoxStatusFeixadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusFeixadaActionPerformed
        if(!jCheckBoxStatusFeixada.isSelected())
        {
         jCheckBoxContasStatus.setSelected(false);
        }
        else
        {
         jCheckBoxStatusAberta.setSelected(false);
         jCheckBoxStatusTodas.setSelected(false);
         jCheckBoxContasStatus.setSelected(true);
        } 
    }//GEN-LAST:event_jCheckBoxStatusFeixadaActionPerformed

    private void jCheckBoxContasStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContasStatusActionPerformed
      if(!jCheckBoxContasStatus.isSelected())
      {
        jCheckBoxStatusAberta.setSelected(false);
        jCheckBoxStatusFeixada.setSelected(false);
        jCheckBoxStatusTodas.setSelected(false);  
      }
      else 
      {
       jCheckBoxStatusTodas.setSelected(true);
      }
    }//GEN-LAST:event_jCheckBoxContasStatusActionPerformed

    private void jComboBoxFimAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFimAnoActionPerformed
      if(!jCheckBoxContasPeriodo.isSelected())
        {
            jCheckBoxContasPeriodo.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxFimAnoActionPerformed

    private void jCheckBoxContasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContasPeriodoActionPerformed
      
        if(!jCheckBoxContasPeriodo.isSelected())
        {
            
         jComboBoxInicioDia.setSelectedIndex(0);
         jComboBoxInicioMes.setSelectedIndex(0);
         jComboBoxInicioAno.setSelectedIndex(0);
         
         jComboBoxFimDia.setSelectedIndex(0);
         jComboBoxFimMes.setSelectedIndex(0);
         jComboBoxFimAno.setSelectedIndex(0);
         jCheckBoxContasPeriodo.setSelected(false);
        }
        
        
    }//GEN-LAST:event_jCheckBoxContasPeriodoActionPerformed

    private void jComboBoxInicioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInicioDiaActionPerformed
        if(!jCheckBoxContasPeriodo.isSelected())
        {
            jCheckBoxContasPeriodo.setSelected(true);
        }
        
    }//GEN-LAST:event_jComboBoxInicioDiaActionPerformed

    private void jComboBoxInicioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInicioMesActionPerformed
        if(!jCheckBoxContasPeriodo.isSelected())
        {
            jCheckBoxContasPeriodo.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxInicioMesActionPerformed

    private void jComboBoxInicioAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInicioAnoActionPerformed
       if(!jCheckBoxContasPeriodo.isSelected())
        {
            jCheckBoxContasPeriodo.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxInicioAnoActionPerformed

    private void jComboBoxFimDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFimDiaActionPerformed
       if(!jCheckBoxContasPeriodo.isSelected())
        {
            jCheckBoxContasPeriodo.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxFimDiaActionPerformed

    private void jComboBoxFimMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFimMesActionPerformed
      if(!jCheckBoxContasPeriodo.isSelected())
        {
         jCheckBoxContasPeriodo.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxFimMesActionPerformed

    private void jCheckBoxContasSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContasSocioActionPerformed
       if(!jCheckBoxContasSocio.isSelected())
       { 
        jComboBoxSocio.setSelectedIndex(0);
        jCheckBoxContasSocio.setSelected(false);
       }
    }//GEN-LAST:event_jCheckBoxContasSocioActionPerformed

    private void jCheckBoxContasLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContasLogradouroActionPerformed
       if(!jCheckBoxContasLogradouro.isSelected())
       {
        jComboBoxLogradouro.setSelectedIndex(0);
        jCheckBoxContasLogradouro.setSelected(false);
       }
    }//GEN-LAST:event_jCheckBoxContasLogradouroActionPerformed

    private void jComboBoxLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLogradouroActionPerformed
       if(!jCheckBoxContasLogradouro.isSelected())
       {
           jCheckBoxContasLogradouro.setSelected(true);
       }
    }//GEN-LAST:event_jComboBoxLogradouroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String data       = "";
        String status     = "";
        String socio      = "";
        String logradouro = "";
        
        if(jCheckBoxContasPeriodo.isSelected())
        {
         if(
         (jComboBoxInicioDia.getSelectedIndex() != 0)&&
         (jComboBoxInicioMes.getSelectedIndex() != 0)&&
         (jComboBoxInicioAno.getSelectedIndex() != 0)&&
         (jComboBoxFimDia.getSelectedIndex()    != 0)&&
         (jComboBoxFimMes.getSelectedIndex()    != 0)&&
         (jComboBoxFimAno.getSelectedIndex()    != 0))
         {
          data =
           jComboBoxInicioDia.getSelectedItem().toString()+
           jComboBoxInicioMes.getSelectedItem().toString()+
           jComboBoxInicioAno.getSelectedItem().toString()+
           jComboBoxFimDia.getSelectedItem().toString()+
           jComboBoxFimMes.getSelectedItem().toString()+
           jComboBoxFimAno.getSelectedItem().toString();
         }
         else
         {
          JOptionPane.showMessageDialog(null, "Você precisa selecionar a data corretamente");
          jComboBoxInicioDia.setSelectedIndex(0);
          jComboBoxInicioMes.setSelectedIndex(0);
          jComboBoxInicioAno.setSelectedIndex(0);
          jComboBoxFimDia.setSelectedIndex(0);
          jComboBoxFimMes.setSelectedIndex(0);
          jComboBoxFimAno.setSelectedIndex(0);
          jCheckBoxContasPeriodo.setSelected(false);
         }
         if(jCheckBoxContasStatus.isSelected())
         {   
           if(jCheckBoxStatusAberta.isSelected()) {status="aberto";}
           if(jCheckBoxStatusFeixada.isSelected()){status="feixado";}
           if(jCheckBoxStatusTodas.isSelected())  {status="todos";}
         }
         if(jCheckBoxContasSocio.isSelected())
         {
          socio = jComboBoxSocio.getSelectedItem().toString();
         }
         if(jCheckBoxContasLogradouro.isSelected())
         {
          logradouro = jComboBoxLogradouro.getSelectedItem().toString();
         }
         
         System.out.println
         (
         "\ndata       " + data  + 
         "\nSocio      " + socio + 
         "\nStatus     " + status +
         "\nlogradouro " + logradouro     
         );
                     
       }    
        try {
          Connection con = HibernateUtil.getConnection();
         // JasperCompileManager.compileReportToFile("src/relatorios/RelatorioContasAbertasPorSocio.jrxml");
          JasperPrint jasperprint =  JasperFillManager.fillReport("src/relatorios/relatorioContasAbertasPorSocio.jasper",null, con);
          JRExporter exp = new JRPdfExporter();
          exp.setParameter(JRExporterParameter.JASPER_PRINT, jasperprint);
          exp.setParameter(JRExporterParameter.OUTPUT_STREAM, new FileOutputStream("conta.pdf") );
          exp.exportReport();
          
         } catch (JRException ex) {
          Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
         } catch (Exception ex) {
          Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxContasLogradouro;
    private javax.swing.JCheckBox jCheckBoxContasPeriodo;
    private javax.swing.JCheckBox jCheckBoxContasSocio;
    private javax.swing.JCheckBox jCheckBoxContasStatus;
    private javax.swing.JCheckBox jCheckBoxStatusAberta;
    private javax.swing.JCheckBox jCheckBoxStatusFeixada;
    private javax.swing.JCheckBox jCheckBoxStatusTodas;
    private javax.swing.JComboBox jComboBoxFimAno;
    private javax.swing.JComboBox jComboBoxFimDia;
    private javax.swing.JComboBox jComboBoxFimMes;
    private javax.swing.JComboBox jComboBoxInicioAno;
    private javax.swing.JComboBox jComboBoxInicioDia;
    private javax.swing.JComboBox jComboBoxInicioMes;
    private javax.swing.JComboBox jComboBoxLogradouro;
    private javax.swing.JComboBox jComboBoxSocio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
   
    // End of variables declaration//GEN-END:variables
}
