/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.DaoPessoa;
import entidades.Pessoa;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliss_000
 */
public class TelaPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisa
     */
    
    TelaCadastros telaCadastro;
    public TelaPesquisa() {
        initComponents();
       
       
         setSize(Toolkit.getDefaultToolkit().getScreenSize().height, Toolkit.getDefaultToolkit().getScreenSize().width/2);       
       
    }
    public TelaPesquisa(TelaCadastros telaCadastro){
        
        this();
        this.telaCadastro = telaCadastro;
        
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "CPF", "Cidade", "Data Nascimento", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Pesquisar");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.gif"))); // NOI18N
        jButtonPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonPesquisa)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

      DefaultTableModel model; 
     
      
      
      if(!jTextField1.getText().isEmpty()){
          ArrayList<Pessoa> p1 =  (ArrayList)new DaoPessoa().BuscarPessoaLikeNome(jTextField1.getText());
          model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
          if(!p1.isEmpty()){
          for(Pessoa p : p1){
          if(p.getDataNasc() != null){
          model.addRow(new Object[]{p.getNome(),p.getSobrenome(),p.getCpf(),p.getCidade(),SimpleDateFormat.getDateInstance().format(p.getDataNasc()),p.getEmail(),p.getStatus()});
          }else{
           model.addRow(new Object[]{p.getNome(),p.getSobrenome(),p.getCpf(),p.getCidade(),"nulo",p.getEmail(),p.getStatus()});   
          }
          }}else{
              
              JOptionPane.showMessageDialog(this, "Nenhuma pessoa encontrada");
          }
      }else if(jTextField1.getText().equals("")){
          
          ArrayList<Pessoa> pessoas = (ArrayList)new DaoPessoa().BuscarTodos();
          model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
          for(Pessoa pessoa : pessoas){
              
           if(pessoa.getDataNasc() != null){
          model.addRow(new Object[]{pessoa.getNome(),pessoa.getSobrenome(),pessoa.getCpf(),pessoa.getCidade(),SimpleDateFormat.getDateInstance().format(pessoa.getDataNasc()),pessoa.getEmail(),pessoa.getStatus()});
          }else{
           model.addRow(new Object[]{pessoa.getNome(),pessoa.getSobrenome(),pessoa.getCpf(),pessoa.getCidade(),"nulo",pessoa.getEmail(),pessoa.getStatus()});   
          }
              
              
          }
      }else{
          
           JOptionPane.showMessageDialog(this,"Pessoa não encontrada");
      }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        telaCadastro.setEnabled(true);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        if(evt.getClickCount() > 1){
           
           
          telaCadastro.preencherAbaFuncionarios(new DaoPessoa().BuscarPessoaNome((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
          telaCadastro.jButtonFuncionarioApagar.setEnabled(true);
          telaCadastro.jButtonFuncionarioEditar.setEnabled(true);
          telaCadastro.setEnabled(true);
          telaCadastro.setVisible(true);
          dispose();
          
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        
          DefaultTableModel model; 
     
      
      
      if(!jTextField1.getText().isEmpty()){
          ArrayList<Pessoa> p1 =  (ArrayList)new DaoPessoa().BuscarPessoaLikeNome(jTextField1.getText());
          model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
          if(!p1.isEmpty()){
          for(Pessoa p : p1){
          if(p.getDataNasc() != null){
          model.addRow(new Object[]{p.getNome(),p.getSobrenome(),p.getCpf(),p.getCidade(),SimpleDateFormat.getDateInstance().format(p.getDataNasc()),p.getEmail(),p.getStatus()});
          }else{
           model.addRow(new Object[]{p.getNome(),p.getSobrenome(),p.getCpf(),p.getCidade(),"nulo",p.getEmail(),p.getStatus()});   
          }
          }}else{
              
              JOptionPane.showMessageDialog(this, "Nenhuma pessoa encontrada");
          }
      }else if(jTextField1.getText().equals("")){
          
          ArrayList<Pessoa> pessoas = (ArrayList)new DaoPessoa().BuscarTodos();
          model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
          for(Pessoa pessoa : pessoas){
              
           if(pessoa.getDataNasc() != null){
          model.addRow(new Object[]{pessoa.getNome(),pessoa.getSobrenome(),pessoa.getCpf(),pessoa.getCidade(),SimpleDateFormat.getDateInstance().format(pessoa.getDataNasc()),pessoa.getEmail(),pessoa.getStatus()});
          }else{
           model.addRow(new Object[]{pessoa.getNome(),pessoa.getSobrenome(),pessoa.getCpf(),pessoa.getCidade(),"nulo",pessoa.getEmail(),pessoa.getStatus()});   
           }
              
              
          }
      }else{
          
           JOptionPane.showMessageDialog(this,"Pessoa não encontrada");
      }
          
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
