/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.DaoCategoriaSocio;
import dao.DaoCheque;
import dao.DaoContasMensais;
import dao.DaoContaslog;
import dao.DaoPessoa;
import dao.DaoUsuario;
import entidades.Categoriasocio;
import entidades.Cheque;
import entidades.Conta;
import entidades.Contaslog;
import entidades.Funcionario;
import entidades.Motivodespesa;
import entidades.Pessoa;
import entidades.Taxa;
import entidades.Usuario;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Scanner;
/**
 *
 * @author alexandre
 */
public class TelaTestes extends javax.swing.JFrame {

    /**
     * Creates new form Testes
     */
    public TelaTestes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Testar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int op = 7;
        
        //categoria Socio
          Categoriasocio cs = new Categoriasocio();   
          DaoCategoriaSocio dcs = new DaoCategoriaSocio();
          Taxa t = new Taxa();
          List<Categoriasocio> categorias = new ArrayList();
          //cheque 
          Cheque cheque = new Cheque();
          DaoCheque dc = new DaoCheque();
          Funcionario f = new Funcionario();
          f.setId(1);
          Motivodespesa md = new Motivodespesa();
          md.setId(7);
          //contas log
           DaoContaslog dcl = new DaoContaslog(); 
          Contaslog cl = new Contaslog();
            List<Contaslog> listalog ;
           
           
          Date data = new Date();
          
          switch(op)
        {
         case (1):
         
          cs.setNome("as");
          cs.setDescricao("descricao de teste");
          t.setId(20);
          cs.setTaxasId(t);
          
          dcs.AdicionarCategoria(cs);
         break; 
          case(2):
          cs.setId(13);
          cs.setNome("e");
          t.setId(20);
          cs.setTaxasId(t);     
          dcs.ApagarCategoria(cs);
         break;
          case(3):
          //buscar todas as categorias
          categorias = dcs.BuscarTodasCategorias();
          for(Categoriasocio s : categorias)
          {
              System.out.println(s.getNome());
          }
          break;
          case(4):
           cheque.setValor(BigDecimal.ONE);
           cheque.setNumero(1);
           
           cheque.setIdFuncionario(f);
           cheque.setIdMotivoDespesa(md);
           cheque.setDataPagamento(data);
           cheque.setDataVencimento(data);
           
           
           dc.AdicionarCheque(cheque);
          break;
          case(5):
           cheque = dc.ChequesId(6);
           System.out.println(cheque.getValor()); 
           break;
          case(6):
         
            
          listalog = dcl.ListarTodas();
          for(Contaslog c : listalog)
          {
              System.out.print(c.getId()+" ");
              System.out.print(c.getDataPag()+" ");
              System.out.print(c.getDataVence()+" ");
              System.out.print(c.getTaxaRelogio()+" ");
              System.out.print(c.getTaxaSocio()+" ");
              System.out.println(c.getTipo());
          }
  
          break;
              case(7):
         
            listalog= dcl.ListarPorTipo("insert");
          
          for(Contaslog c : listalog)
          {
              System.out.print(c.getId()+" ");
              System.out.print(c.getDataPag()+" ");
              System.out.print(c.getDataVence()+" ");
              System.out.print(c.getTaxaRelogio()+" ");
              System.out.print(c.getTaxaSocio()+" ");
              System.out.println(c.getTipo());
          }
  
          break;       
              
              
          case(8):
             cl = dcl.ListarPorId(1);
              System.out.print(cl.getId()+" ");
              System.out.print(cl.getDataPag()+" ");
              System.out.print(cl.getDataVence()+" ");
              System.out.print(cl.getTaxaRelogio()+" ");
              System.out.print(cl.getTaxaSocio()+" ");
              System.out.println(cl.getTipo());
              
          break;    
          }
          
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTestes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
