/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.DaoPessoa;
import entidades.Endereco;
import entidades.Pessoa;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alexandre
 */
public class TelaCadastros extends javax.swing.JFrame {

    JFrame telaPrincipal;
    List<Endereco> enderecos;

    /**
     * Creates new form TelaCadastros
     */
    public TelaCadastros() {

        initComponents();
        editableTextFields(false);
         
    }

    public TelaCadastros(JFrame telaPrincipal) {

        this();
        this.telaPrincipal = telaPrincipal;
        this.telaPrincipal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acal2000PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("acal2002PU").createEntityManager();
        enderecoQuery = java.beans.Beans.isDesignTime() ? null : acal2000PUEntityManager.createQuery("SELECT e FROM Endereco e");
        enderecoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : enderecoQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelLog = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoLogradouro = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoLogradouro = new javax.swing.JComboBox();
        jTextFieldNomeLograduro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonEnviarLogradouro = new javax.swing.JButton();
        jPanelFunc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFuncionarioNome = new javax.swing.JTextField();
        jTextFieldFuncionarioSobrenome = new javax.swing.JTextField();
        jTextFieldFuncionarioApelido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFuncionarioTelefone = new javax.swing.JTextField();
        jTextFieldFuncionarioEmail = new javax.swing.JTextField();
        jTextFieldFuncionarioDataNascimento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldFuncionarioNomedame = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldFuncionarioID = new javax.swing.JTextField();
        jComboBoxFuncionarioSexo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldFuncionarioNomedopai = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldFuncionarioRgnumero = new javax.swing.JTextField();
        jTextFieldFuncionarioOrgaoExpedidor = new javax.swing.JTextField();
        jTextFieldFuncionarioDatadeemissao = new javax.swing.JTextField();
        jButtonFuncionarioPesquisar = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxFuncionarioLograduro = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldFuncionarioNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFuncionarioBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldFuncionarioCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldFuncionarioCep = new javax.swing.JTextField();
        Logradouro = new javax.swing.JLabel();
        jComboBoxFuncionarioUf = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        Logradouro1 = new javax.swing.JLabel();
        Logradouro2 = new javax.swing.JLabel();
        Logradouro3 = new javax.swing.JLabel();
        jTextFieldFuncionarioNumeroDaMatricula = new javax.swing.JTextField();
        jTextFieldFuncionarioCategoriaSocio = new javax.swing.JTextField();
        jComboBoxFuncionarioStatus = new javax.swing.JComboBox();
        jButtonFuncionarioEditar = new javax.swing.JButton();
        jButtonFuncionarioApagar = new javax.swing.JButton();
        jButtonFuncionarioSalvar = new javax.swing.JButton();
        jButtonFuncionarioNovo = new javax.swing.JButton();
        jButtonFuncionarioCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Logradouro4 = new javax.swing.JLabel();
        Logradouro5 = new javax.swing.JLabel();
        Logradouro6 = new javax.swing.JLabel();
        Logradouro7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFuncionarioObservacoes = new javax.swing.JTextArea();
        jTextFieldFuncionarioCargo = new javax.swing.JTextField();
        jTextFieldFuncionarioSalario = new javax.swing.JTextField();
        jTextFieldFuncionarioDataDeContratacao = new javax.swing.JTextField();
        jPanelReceitas = new javax.swing.JPanel();
        jPanelSocio = new javax.swing.JPanel();
        jPanelCategoria_Socio = new javax.swing.JPanel();
        jPanelTipoDespesa = new javax.swing.JPanel();
        jPanelDespesa = new javax.swing.JPanel();
        jPanelTipoReceita = new javax.swing.JPanel();
        jPanelReceita = new javax.swing.JPanel();
        jPanelCheques = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanelContrato = new javax.swing.JPanel();
        jPanelTaxas = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImage(new ImageIcon(getClass().getResource("/img/ico.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanelLog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelLog.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Logradouros"));

        jTextAreaDescricaoLogradouro.setColumns(20);
        jTextAreaDescricaoLogradouro.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoLogradouro);

        jLabel3.setText("Descrição");

        jLabel1.setText("Tipo");

        jComboBoxTipoLogradouro.setModel(new javax.swing.DefaultComboBoxModel(
            new String[] {
                "AEROPORTO",
                "APARTAMENTO",
                "AVENIDA",
                "BECO",
                "BLOCO",
                "CAMINHO",
                "ESCADINHA",
                "ESTAÇÃO",
                "ESTRADA",
                "FAZENDA",
                "LADEIRA",
                "LARGO",
                "PRAÇA",
                "PARQUE",
                "QUADRA",
                "QUILÔMETRO",
                "QUINTA",
                "RODOVIA",
                "RUA",
                "TRAVESSA"
            }));
            jComboBoxTipoLogradouro.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBoxTipoLogradouroActionPerformed(evt);
                }
            });

            jLabel2.setText("Nome");

            jButtonEnviarLogradouro.setText("Enviar");
            jButtonEnviarLogradouro.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonEnviarLogradouroActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButtonEnviarLogradouro))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jComboBoxTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNomeLograduro))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))))
                    .addGap(108, 108, 108))
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeLograduro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                    .addComponent(jButtonEnviarLogradouro)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanelLogLayout = new javax.swing.GroupLayout(jPanelLog);
            jPanelLog.setLayout(jPanelLogLayout);
            jPanelLogLayout.setHorizontalGroup(
                jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanelLogLayout.setVerticalGroup(
                jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(409, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Logradouros", null, jPanelLog, "Cadastre um logradouro");
            jPanelLog.getAccessibleContext().setAccessibleDescription("");

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Pessoais"));

            jLabel6.setText("Sobrenome");

            jLabel5.setText("Nome");

            jTextFieldFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextFieldFuncionarioNomeActionPerformed(evt);
                }
            });

            jLabel7.setText("Apelido");

            jLabel4.setText("Telefone");

            jLabel13.setText("Email");

            jLabel14.setText("Data Nascimento");

            jLabel16.setText("Nome da Mãe");

            jLabel18.setText("ID");

            jTextFieldFuncionarioID.setEditable(false);
            jTextFieldFuncionarioID.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextFieldFuncionarioIDActionPerformed(evt);
                }
            });

            jComboBoxFuncionarioSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino","Feminino" }));

            jLabel19.setText("Sexo");

            jLabel20.setText("Cpf");

            jLabel21.setText("Rg Numero");

            jLabel22.setText("Orgão Expedidor");

            jLabel24.setText("Data de Emissao");

            jLabel27.setText("Nome do Pai");

            jButtonFuncionarioPesquisar.setText("Pesquisar");
            jButtonFuncionarioPesquisar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonFuncionarioPesquisarActionPerformed(evt);
                }
            });

            try {
                jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(43, 43, 43)
                    .addComponent(jTextFieldFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextFieldFuncionarioEmail)
                    .addGap(186, 186, 186))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFuncionarioSobrenome)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonFuncionarioPesquisar)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(54, 54, 54)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFuncionarioApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFuncionarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24))
                .addComponent(jSeparator1)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addGap(18, 18, 18)
                    .addComponent(jTextFieldFuncionarioNomedame)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextFieldFuncionarioNomedopai)
                    .addGap(15, 15, 15))
                .addComponent(jSeparator2)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldFuncionarioRgnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFuncionarioOrgaoExpedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFuncionarioDatadeemissao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldFuncionarioDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxFuncionarioSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonFuncionarioPesquisar))
                            .addGap(8, 8, 8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldFuncionarioSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFuncionarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldFuncionarioApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldFuncionarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldFuncionarioDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jComboBoxFuncionarioSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextFieldFuncionarioNomedame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(jTextFieldFuncionarioNomedopai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jTextFieldFuncionarioRgnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jTextFieldFuncionarioOrgaoExpedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jTextFieldFuncionarioDatadeemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

            jLabel8.setText("Número");

            jLabel9.setText("Bairro");

            jLabel10.setText("Cidade");

            jLabel11.setText("UF");

            jLabel12.setText("CEP");

            Logradouro.setText("Logradouro");

            jComboBoxFuncionarioUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
                "AC",
                "AL",
                "AP",
                "AM",
                "BA",
                "CE",
                "DF",
                "ES",
                "GO",
                "MA",
                "MT",
                "MS",
                "MG",
                "PA",
                "PB",
                "PR",
                "PE",
                "PI",
                "RJ",
                "RN",
                "RS",
                "RO",
                "RR",
                "SC",
                "SE",
                "TO"
            }));

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(Logradouro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxFuncionarioLograduro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTextFieldFuncionarioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addComponent(jTextFieldFuncionarioBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFuncionarioCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxFuncionarioUf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldFuncionarioCep, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldFuncionarioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldFuncionarioCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBoxFuncionarioUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextFieldFuncionarioCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logradouro)
                        .addComponent(jComboBoxFuncionarioLograduro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes Especiais"));

            Logradouro1.setText("Status");

            Logradouro2.setText("Categoria Socio");

            Logradouro3.setText("Numero da Matricula");

            jComboBoxFuncionarioStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Desativar" }));

            jButtonFuncionarioEditar.setText("Editar");

            jButtonFuncionarioApagar.setText("Apagar");

            jButtonFuncionarioSalvar.setText("Salvar");

            jButtonFuncionarioNovo.setText("Novo");
            jButtonFuncionarioNovo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonFuncionarioNovoActionPerformed(evt);
                }
            });

            jButtonFuncionarioCancelar.setText("Cancelar");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(Logradouro1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxFuncionarioStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Logradouro2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldFuncionarioCategoriaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(Logradouro3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldFuncionarioNumeroDaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButtonFuncionarioNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFuncionarioEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFuncionarioApagar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFuncionarioSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFuncionarioCancelar)))
                    .addContainerGap(44, Short.MAX_VALUE))
            );

            jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonFuncionarioApagar, jButtonFuncionarioCancelar, jButtonFuncionarioEditar, jButtonFuncionarioNovo, jButtonFuncionarioSalvar});

            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logradouro1)
                        .addComponent(Logradouro2)
                        .addComponent(Logradouro3)
                        .addComponent(jTextFieldFuncionarioNumeroDaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFuncionarioCategoriaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxFuncionarioStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFuncionarioEditar)
                        .addComponent(jButtonFuncionarioApagar)
                        .addComponent(jButtonFuncionarioSalvar)
                        .addComponent(jButtonFuncionarioNovo)
                        .addComponent(jButtonFuncionarioCancelar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonFuncionarioApagar, jButtonFuncionarioCancelar, jButtonFuncionarioEditar, jButtonFuncionarioNovo, jButtonFuncionarioSalvar});

            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes do Funcionario"));
            jPanel5.setToolTipText("");

            Logradouro4.setText("Cargo");

            Logradouro5.setText("Salario");

            Logradouro6.setText("Data de Contratação");

            Logradouro7.setText("Observações");

            jTextAreaFuncionarioObservacoes.setColumns(20);
            jTextAreaFuncionarioObservacoes.setRows(5);
            jScrollPane2.setViewportView(jTextAreaFuncionarioObservacoes);

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Logradouro5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldFuncionarioSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(Logradouro4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldFuncionarioCargo)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logradouro7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Logradouro6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFuncionarioDataDeContratacao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Logradouro4)
                                    .addComponent(jTextFieldFuncionarioCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Logradouro7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Logradouro5)
                                .addComponent(jTextFieldFuncionarioSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)
                            .addComponent(Logradouro6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFuncionarioDataDeContratacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(21, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanelFuncLayout = new javax.swing.GroupLayout(jPanelFunc);
            jPanelFunc.setLayout(jPanelFuncLayout);
            jPanelFuncLayout.setHorizontalGroup(
                jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFuncLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanelFuncLayout.setVerticalGroup(
                jPanelFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFuncLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jTabbedPane1.addTab("Funcionários", jPanelFunc);

            javax.swing.GroupLayout jPanelReceitasLayout = new javax.swing.GroupLayout(jPanelReceitas);
            jPanelReceitas.setLayout(jPanelReceitasLayout);
            jPanelReceitasLayout.setHorizontalGroup(
                jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelReceitasLayout.setVerticalGroup(
                jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Receitas", jPanelReceitas);

            javax.swing.GroupLayout jPanelSocioLayout = new javax.swing.GroupLayout(jPanelSocio);
            jPanelSocio.setLayout(jPanelSocioLayout);
            jPanelSocioLayout.setHorizontalGroup(
                jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelSocioLayout.setVerticalGroup(
                jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Sócio", jPanelSocio);

            javax.swing.GroupLayout jPanelCategoria_SocioLayout = new javax.swing.GroupLayout(jPanelCategoria_Socio);
            jPanelCategoria_Socio.setLayout(jPanelCategoria_SocioLayout);
            jPanelCategoria_SocioLayout.setHorizontalGroup(
                jPanelCategoria_SocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelCategoria_SocioLayout.setVerticalGroup(
                jPanelCategoria_SocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Categoria Sócio", jPanelCategoria_Socio);

            javax.swing.GroupLayout jPanelTipoDespesaLayout = new javax.swing.GroupLayout(jPanelTipoDespesa);
            jPanelTipoDespesa.setLayout(jPanelTipoDespesaLayout);
            jPanelTipoDespesaLayout.setHorizontalGroup(
                jPanelTipoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelTipoDespesaLayout.setVerticalGroup(
                jPanelTipoDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Tipo/Despesa", jPanelTipoDespesa);

            javax.swing.GroupLayout jPanelDespesaLayout = new javax.swing.GroupLayout(jPanelDespesa);
            jPanelDespesa.setLayout(jPanelDespesaLayout);
            jPanelDespesaLayout.setHorizontalGroup(
                jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelDespesaLayout.setVerticalGroup(
                jPanelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Despesa", jPanelDespesa);

            javax.swing.GroupLayout jPanelTipoReceitaLayout = new javax.swing.GroupLayout(jPanelTipoReceita);
            jPanelTipoReceita.setLayout(jPanelTipoReceitaLayout);
            jPanelTipoReceitaLayout.setHorizontalGroup(
                jPanelTipoReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelTipoReceitaLayout.setVerticalGroup(
                jPanelTipoReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Tipo/Receita", jPanelTipoReceita);

            javax.swing.GroupLayout jPanelReceitaLayout = new javax.swing.GroupLayout(jPanelReceita);
            jPanelReceita.setLayout(jPanelReceitaLayout);
            jPanelReceitaLayout.setHorizontalGroup(
                jPanelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelReceitaLayout.setVerticalGroup(
                jPanelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Receita", jPanelReceita);

            jLabel26.setText("Id");

            jLabel28.setText("Valor");

            jLabel29.setText("Data de Vencimento");

            jLabel30.setText("Numero");

            javax.swing.GroupLayout jPanelChequesLayout = new javax.swing.GroupLayout(jPanelCheques);
            jPanelCheques.setLayout(jPanelChequesLayout);
            jPanelChequesLayout.setHorizontalGroup(
                jPanelChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelChequesLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(jPanelChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel30)
                        .addComponent(jLabel29)
                        .addComponent(jLabel28)
                        .addComponent(jLabel26))
                    .addContainerGap(555, Short.MAX_VALUE))
            );
            jPanelChequesLayout.setVerticalGroup(
                jPanelChequesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelChequesLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel26)
                    .addGap(69, 69, 69)
                    .addComponent(jLabel28)
                    .addGap(43, 43, 43)
                    .addComponent(jLabel29)
                    .addGap(35, 35, 35)
                    .addComponent(jLabel30)
                    .addContainerGap(423, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Cheques", jPanelCheques);

            javax.swing.GroupLayout jPanelContratoLayout = new javax.swing.GroupLayout(jPanelContrato);
            jPanelContrato.setLayout(jPanelContratoLayout);
            jPanelContratoLayout.setHorizontalGroup(
                jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 693, Short.MAX_VALUE)
            );
            jPanelContratoLayout.setVerticalGroup(
                jPanelContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 668, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Contrato", jPanelContrato);

            jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Taxas"));

            jLabel15.setText("Id");

            jLabel17.setText("Nome");

            jLabel23.setText("Descrição");

            jLabel25.setText("Valor");

            jTextArea2.setColumns(20);
            jTextArea2.setRows(5);
            jScrollPane3.setViewportView(jTextArea2);

            javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
            jPanel13.setLayout(jPanel13Layout);
            jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addContainerGap())
            );
            jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jLabel25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanelTaxasLayout = new javax.swing.GroupLayout(jPanelTaxas);
            jPanelTaxas.setLayout(jPanelTaxasLayout);
            jPanelTaxasLayout.setHorizontalGroup(
                jPanelTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanelTaxasLayout.setVerticalGroup(
                jPanelTaxasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTaxasLayout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 364, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Taxas", jPanelTaxas);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        telaPrincipal.setEnabled(true);
        telaPrincipal.toFront();

    }//GEN-LAST:event_formWindowClosed

    private void jTextFieldFuncionarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioIDActionPerformed

    private void jComboBoxTipoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoLogradouroActionPerformed

    private void jButtonFuncionarioNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioNovoActionPerformed
        editableTextFields(true);
    }//GEN-LAST:event_jButtonFuncionarioNovoActionPerformed

    private void jTextFieldFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioNomeActionPerformed
       
        
        String nome = jTextFieldFuncionarioNome.getText();
        if(nome.matches("\\w+\\s\\w+")){
         Pessoa pessoa = new DaoPessoa().BuscarNomeCompleto(jTextFieldFuncionarioNome.getText());
         if(pessoa != null){
             
             preencherAbaFuncionarios(pessoa);
            
             
             
         }else{
             
             JOptionPane.showMessageDialog(null,"Funcionário não encontrado");
             jTextFieldFuncionarioNome.setText("");
         }
         
        }else{
            
            JOptionPane.showMessageDialog(this, "Para fazer uma pesquisa por nome é necessário digitar o sobrenome");
        }
        
    }//GEN-LAST:event_jTextFieldFuncionarioNomeActionPerformed

    private void jButtonFuncionarioPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioPesquisarActionPerformed
      
        
    
    }//GEN-LAST:event_jButtonFuncionarioPesquisarActionPerformed

    private void jButtonEnviarLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarLogradouroActionPerformed
       
        Endereco endereco = new Endereco();
        
        String nomeLogradouro = jTextFieldNomeLograduro.getText();
        String tipoLogradouro = (String) jComboBoxTipoLogradouro.getSelectedItem();
        String descricaoLogradouro = jTextAreaDescricaoLogradouro.getText();
        
        System.out.println(nomeLogradouro + tipoLogradouro + descricaoLogradouro);
        
    }//GEN-LAST:event_jButtonEnviarLogradouroActionPerformed

    
    private void editableTextFields(boolean editable){
        
        jTextFieldFuncionarioApelido.setEditable(editable);
        jTextFieldFuncionarioBairro.setEditable(editable);
        jTextFieldFuncionarioCargo.setEditable(editable);
        jTextFieldFuncionarioCategoriaSocio.setEditable(editable);
        jTextFieldFuncionarioCep.setEditable(editable);
        jTextFieldFuncionarioCidade.setEditable(editable);
        jFormattedTextField1.setEditable(editable);
        jTextFieldFuncionarioDataDeContratacao.setEditable(editable);
        jTextFieldFuncionarioDataNascimento.setEditable(editable);
        jTextFieldFuncionarioDatadeemissao.setEditable(editable);
        jTextFieldFuncionarioEmail.setEditable(editable);
        jTextFieldFuncionarioNomedame.setEditable(editable);
        jTextFieldFuncionarioNomedopai.setEditable(editable);
        jTextFieldFuncionarioNumero.setEditable(editable);
        jTextFieldFuncionarioNumeroDaMatricula.setEditable(editable);
        jTextFieldFuncionarioOrgaoExpedidor.setEditable(editable);
        jTextFieldFuncionarioRgnumero.setEditable(editable);
        jTextFieldFuncionarioSalario.setEditable(editable);
        jTextFieldFuncionarioSobrenome.setEditable(editable);
        jTextFieldFuncionarioTelefone.setEditable(editable);
        jComboBoxFuncionarioLograduro.setEnabled(editable);
        jComboBoxFuncionarioSexo.setEnabled(editable);
        jComboBoxFuncionarioStatus.setEnabled(editable);
        jComboBoxFuncionarioUf.setEnabled(editable);
        jButtonFuncionarioApagar.setEnabled(editable);
        jButtonFuncionarioCancelar.setEnabled(editable);
        jButtonFuncionarioEditar.setEnabled(editable);
        jButtonFuncionarioSalvar.setEnabled(editable);
    }
    
    private void preencherAbaFuncionarios(Pessoa pessoa){
        
        
         jTextFieldFuncionarioNome.setText(pessoa.getNome());   
         jTextFieldFuncionarioID.setText(String.valueOf(pessoa.getId()));
         jTextFieldFuncionarioSobrenome.setText(pessoa.getSobrenome());
         jTextFieldFuncionarioApelido.setText(pessoa.getApelido());
         jTextFieldFuncionarioTelefone.setText(pessoa.getTelefone());
         jTextFieldFuncionarioEmail.setText(pessoa.getEmail());
         if(pessoa.getDataNasc() != null){
         jTextFieldFuncionarioDataNascimento.setText( SimpleDateFormat.getDateInstance().format(pessoa.getDataNasc()));
         }
         jComboBoxFuncionarioSexo.setSelectedItem(pessoa.getSexo());
         jTextFieldFuncionarioNomedame.setText(pessoa.getNomeMae());
         jTextFieldFuncionarioNomedopai.setText(pessoa.getNomePai());
         jFormattedTextField1.setText(pessoa.getCpf());
         jTextFieldFuncionarioRgnumero.setText(pessoa.getRgNumero());
         jTextFieldFuncionarioOrgaoExpedidor.setText(pessoa.getRgExpedidor());
         if(pessoa.getRgEmissao() != null){
         jTextFieldFuncionarioDatadeemissao.setText(SimpleDateFormat.getDateInstance().format(pessoa.getRgEmissao()));
         }
         jTextFieldFuncionarioCidade.setText(pessoa.getCidade());
         jTextFieldFuncionarioBairro.setText(pessoa.getBairro());
         jComboBoxFuncionarioUf.setSelectedItem(pessoa.getUf());
         jTextFieldFuncionarioCep.setText(pessoa.getCep());
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCadastros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logradouro;
    private javax.swing.JLabel Logradouro1;
    private javax.swing.JLabel Logradouro2;
    private javax.swing.JLabel Logradouro3;
    private javax.swing.JLabel Logradouro4;
    private javax.swing.JLabel Logradouro5;
    private javax.swing.JLabel Logradouro6;
    private javax.swing.JLabel Logradouro7;
    private javax.persistence.EntityManager acal2000PUEntityManager;
    private java.util.List<entidades.Endereco> enderecoList;
    private javax.persistence.Query enderecoQuery;
    private javax.swing.JButton jButtonEnviarLogradouro;
    private javax.swing.JButton jButtonFuncionarioApagar;
    private javax.swing.JButton jButtonFuncionarioCancelar;
    private javax.swing.JButton jButtonFuncionarioEditar;
    private javax.swing.JButton jButtonFuncionarioNovo;
    private javax.swing.JButton jButtonFuncionarioPesquisar;
    private javax.swing.JButton jButtonFuncionarioSalvar;
    private javax.swing.JComboBox jComboBoxFuncionarioLograduro;
    private javax.swing.JComboBox jComboBoxFuncionarioSexo;
    private javax.swing.JComboBox jComboBoxFuncionarioStatus;
    private javax.swing.JComboBox jComboBoxFuncionarioUf;
    private javax.swing.JComboBox jComboBoxTipoLogradouro;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCategoria_Socio;
    private javax.swing.JPanel jPanelCheques;
    private javax.swing.JPanel jPanelContrato;
    private javax.swing.JPanel jPanelDespesa;
    private javax.swing.JPanel jPanelFunc;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JPanel jPanelReceita;
    private javax.swing.JPanel jPanelReceitas;
    private javax.swing.JPanel jPanelSocio;
    private javax.swing.JPanel jPanelTaxas;
    private javax.swing.JPanel jPanelTipoDespesa;
    private javax.swing.JPanel jPanelTipoReceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaDescricaoLogradouro;
    private javax.swing.JTextArea jTextAreaFuncionarioObservacoes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldFuncionarioApelido;
    private javax.swing.JTextField jTextFieldFuncionarioBairro;
    private javax.swing.JTextField jTextFieldFuncionarioCargo;
    private javax.swing.JTextField jTextFieldFuncionarioCategoriaSocio;
    private javax.swing.JTextField jTextFieldFuncionarioCep;
    private javax.swing.JTextField jTextFieldFuncionarioCidade;
    private javax.swing.JTextField jTextFieldFuncionarioDataDeContratacao;
    private javax.swing.JTextField jTextFieldFuncionarioDataNascimento;
    private javax.swing.JTextField jTextFieldFuncionarioDatadeemissao;
    private javax.swing.JTextField jTextFieldFuncionarioEmail;
    private javax.swing.JTextField jTextFieldFuncionarioID;
    private javax.swing.JTextField jTextFieldFuncionarioNome;
    private javax.swing.JTextField jTextFieldFuncionarioNomedame;
    private javax.swing.JTextField jTextFieldFuncionarioNomedopai;
    private javax.swing.JTextField jTextFieldFuncionarioNumero;
    private javax.swing.JTextField jTextFieldFuncionarioNumeroDaMatricula;
    private javax.swing.JTextField jTextFieldFuncionarioOrgaoExpedidor;
    private javax.swing.JTextField jTextFieldFuncionarioRgnumero;
    private javax.swing.JTextField jTextFieldFuncionarioSalario;
    private javax.swing.JTextField jTextFieldFuncionarioSobrenome;
    private javax.swing.JTextField jTextFieldFuncionarioTelefone;
    private javax.swing.JTextField jTextFieldNomeLograduro;
    // End of variables declaration//GEN-END:variables
}
